title: 冲田瑾
description: > # this means to ignore newlines until "baseurl:"
  身不动 能否退却黑暗 花与水
permalink: ':title/'
baseurl: "/Okita-kin.github.io" # the subpath of your site, e.g. /blog
url: "https://Okita-kin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Okita kin # add your name
author-img: 20151126204937_GmBMK0.jpg # add your photo
about-author: 即使没有记忆 即使没有明天    也一定会有办法的 # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: Okita-kin # add your Github handle
linkedin: # add your Linkedin handle
email: akashikin@outlook.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
